### PR TITLE
QueryDynamycallyFunctionAndClass

### PR DESCRIPTION
**Pull request by judicapo**
It would be a good feature, in order to dynamically execute a function and a required CIM, AMT or SIM class

### CODE REVIEW

**Comment by jsastriawan** [comment]
Thanks, this is a good patch. I am still on holiday and I will merge later.

**Comment by jsastriawan** [comment]
Hmm, The intention of api.ashx is for simple one shot WSMAN REST demonstration. Would you like to rewrite your implementation on other end point? 
I am thinking of several use cases at the moment:
- Simple WSMAN GET query
- chain of WSMAN calls to invoke complex command (power control, reboot to BIOS etc)
- Simple WSMAN data update
- WSMAN enumeration

Thanks for your contribution.

**Comment by judicapo** [comment]
Right, I will move it to another endpoint.

My approach is designed to query or execute an AMT action more dynamically. Keeping that in mind, I think that it could be developed in a POST action and explore the capabilities of giving the work of comunicate and interact with an AMT machine to the MPS Server. That would enhance the management of CIRA channels and reduce the necessity of use AMT scripts at external implementations.

**Comment by judicapo** [comment]
Hi there.

Do you have any comments?  😃

**Comment by jsastriawan** [comment]
Great, btw would you be able to add a check to see if there is an established CIRA connection for particular host/guid?

This means the WSMAN call can only be executed if obj.mpsserver.ciraconnections[req.query.host] is not null.

**Pull request merged**
